# pyproject.toml
# This file is used ONLY for tool configurations.
# Dependencies are managed via requirements.txt and requirements-dev.txt.

[tool.ruff]
line-length = 200 # As in your example, adjust if needed

[tool.ruff.lint]
select = ["E", "W", "F", "I", "C", "B", "UP", "PT", "SIM"]
ignore = []
# fixable = ["ALL"] # Optional

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
plugins = ["numpy.typing.mypy_plugin"]
mypy_path = "src" # Correct, as your code is in src/

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=src.main --cov-report=term-missing --cov-fail-under=60" # Updated --cov target to src.main
testpaths = ["tests"]
# log_cli = true # Optional pytest log config
# log_cli_level = "INFO"

[tool.bandit]
# skips = ["B101"] # Example: Skip the assert_used check if needed
# severity_medium_score = 2.0 # Example
# Your existing [tool.bandit] was empty, which is fine. Add specifics if necessary.